version: '3'

services:
  app:
    container_name: ed_app
    build: ./jango
    volumes:
     - ./jango/source:/django
    ports:
     - 80:8000
    image: app:django
    # command: python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    build: ./sql
    container_name: ed_mysql
    volumes:
      - ./sql/data:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: 'django'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd