version: '3'

services:
  app:
    container_name: ed_app
    build: ./jango
    volumes:
     - ./jango/source:/django
    ports:
     - 80:8000
    image: app:django
    # command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db