# Generated by Django 4.1.7 on 2023-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departments',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=150, verbose_name='所属'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
